version: '3'
services:
  node14:
    restart: always
    build: .
    container_name: 'node14'
    working_dir: '/root/'
    tty: true
    ports:
      - "18080:8080"
    volumes:
      - ./opt:/root/opt
